[tool.robotpy]

robotpy_version = "2024.3.2.2"

robotpy_extras = [
    "commands2",
    "navx",
    "pathplannerlib",
    "phoenix6",
    "cscore"
]

# Other pip packages to install
requires = [
    "robotpy-opencv; platform_machine == 'roborio'",
    "opencv-python; platform_machine != 'roborio'"
]
